'use client'

import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from './functions/check-is-public-route';
import PrivateRoute from './componentes/PrivateRoute';
import { isUserAuthenticated } from './componentes/PrivateRoute'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname);
  console.log('rota é pública?' , isPublicPage)
  console.log('Usuario está autenticado?' + isUserAuthenticated)

  return (
    <html lang="pt-BR">
      <body>
        {isPublicPage && children}
        {!isPublicPage && (
          <PrivateRoute>
             {children}
          </PrivateRoute>
        )}
        </body>
    </html>
  )
}
